# ----------------------------
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 pinkabels
# ----------------------------
# config.yaml
# ----------------------------
poll_interval: 600

instagram:
  - bts.bighitofficial
  - rkive
  - jin
  - agustd
  - uarmyhope
  - j.m
  - thv
  - mnijungkook

twitter:
  - BTS_twt
  - bts_bighit

youtube:
  - UCLkAepWjdylmXSltofFvsYQ

youtube_posts:
  - BTS
